version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=fastapi_db
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  mongo_data:
