version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  fastapi_app:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=fastapi_db
    volumes:
      - .:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./celery
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery_worker.celery", "worker"]
    depends_on:
      - redis
      - fastapi
    networks:
      - app-network

  celery-beat:
    build: .
    command: ["celery", "-A", "app.celery_worker.celery", "beat", "--scheduler", "celery.beat.schedulers:PersistentScheduler", "--loglevel=info"]
    depends_on:
      - redis

volumes:
  mongo_data:

  networks:
  app-network:
    driver: bridge
