version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: ["celery", "-A", "app.celery_worker.celery", "worker"]
    depends_on:
      - redis
      - fastapi

  celery-beat:
    build: .
    command: ["celery", "-A", "app.celery_worker.celery", "beat", "--scheduler", "celery.beat.schedulers:PersistentScheduler", "--loglevel=info"]
    depends_on:
      - redis

volumes:
  mongo_data: