version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  fastapi_app:
    build: ./app
    container_name: fastapi_app
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    env_file: '.env'
    volumes:
      - ./app:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery_worker:
    build:
      context: ./celery
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      - redis
      - mongo
    networks:
      - app-network
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]

  celery_beat:
    build:
      context: ./celery
      dockerfile: Dockerfile
    container_name: celery_beat
    depends_on:
      - redis
      - mongo
    networks:
      - app-network
    command: ["celery", "-A", "tasks", "beat", "-l", "info"]

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
