version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  fastapi_app:
    build: ./app
    container_name: fastapi_app
    restart: always
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=fastapi_db
    # env_file:
    #   - .env
    volumes:
      - ./app:/app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  celery:
    build:
      context: ./celery
      dockerfile: Dockerfile
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - fastapi_app
    networks:
      - app-network

  celery-beat:
    build: 
      context: ./celery
      dockerfile: Dockerfile
    command: ["celery", "-A", "tasks", "beat", "--scheduler", "celery.beat.schedulers.PersistentScheduler", "--loglevel=info"]
    depends_on:
      - redis
      - celery
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge