version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo1
      - redis
      - worker

  mongo1:
    image: "mongo"
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
