version: "3.8"

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    networks:
      - app-network 

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./celery
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.celery_worker.celery", "worker"]
    depends_on:
      - redis
      - fastapi
    networks:
      - app-network

  celery-beat:
    build: .
    command: ["celery", "-A", "app.celery_worker.celery", "beat", "--scheduler", "celery.beat.schedulers:PersistentScheduler", "--loglevel=info"]
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge